name: main

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up docker cache
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker
      - name: Set up ccache
        uses: actions/cache@v3
        with:
          path: /tmp/.ccache
          key: ${{ runner.os }}-ccache
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker info
        run: docker info
      - name: Build docker image
        run: docker build -t shajen/sdr-scanner -f Dockerfile .
      - name: Test sdr-scanner
        run: docker run --rm shajen/sdr-scanner /usr/bin/auto_sdr_test
      - name: Run sdr-scanner
        run: docker run --rm shajen/sdr-scanner
      - name: Deploy sdr-scanner tag
        if: github.ref_type == 'tag'
        run: |
          TAG=${GITHUB_REF_NAME/v/}
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} docker.io
          docker image tag shajen/sdr-scanner docker.io/shajen/sdr-scanner:$TAG
          docker image tag shajen/sdr-scanner docker.io/shajen/sdr-scanner
          docker push docker.io/shajen/sdr-scanner:$TAG
          docker push docker.io/shajen/sdr-scanner
